### ISSUE TITLE
Error exporting relations.

### ISSUE THREAD

**Issue by L-I-S-T-A** [fgianoli/RelationshipManager#1]
Hi!
I installed the plugin QGIS version  3.34. When I export my relations, I receive this error message:
"Si è verificato un errore durante l'esecuzione del codice Python: 

AttributeError: 'str' object has no attribute 'name' 
Traceback (most recent call last):
  File "C:\Users/giuli/AppData/Roaming/QGIS/QGIS3\profiles\dbField/python/plugins\relazioniplugin\RelazioniPlugin_dialog.py", line 80, in esporta_relazioni
    relazioni = self.ottieni_relazioni()
  File "C:\Users/giuli/AppData/Roaming/QGIS/QGIS3\profiles\dbField/python/plugins\relazioniplugin\RelazioniPlugin_dialog.py", line 280, in ottieni_relazioni
    'name': relation.name(),
AttributeError: 'str' object has no attribute 'name'

Versione Python: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
Versione di QGIS: 3.34.5-Prizren Prizren, 4b308492 

Percorso Python:
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python
C:/Users/giuli/AppData/Roaming/QGIS/QGIS3\profiles\dbField/python
C:/Users/giuli/AppData/Roaming/QGIS/QGIS3\profiles\dbField/python/plugins
C:/PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.5\apps\grass\grass83\etc\python
C:\Users\giuli\Documents
C:\Program Files\QGIS 3.34.5\bin\python39.zip
C:\PROGRA~1\QGIS33~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.34.5\bin
C:\PROGRA~1\QGIS33~1.5\apps\Python39
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/giuli/AppData/Roaming/QGIS/QGIS3\profiles\dbField/python
C:/Users/giuli/Documents/CARG Fermo"

Thanks!

**Comment by fgianoli** [comment]
Thanks, yes is it a little bug. I'll fix it now. Thanks for your help

Il lun 7 ott 2024, 19:55 L-I-S-T-A ***@***.***> ha scritto:

**Comment by fgianoli** [comment]
The new version of the plugin should fix the error.
Let me know

**Comment by fgianoli** [comment]
fixed
